version: '3'
services:

 service_auth:
  build:
   context: .
   dockerfile: DockerfileProjectServiceAuth
  image: service_auth
  container_name: service_auth

 service_app:
  build:
   context: .
   dockerfile: DockerfileProjectServiceApp
  image: service_app
  container_name: service_app

 webserver:
  image: nginx:alpine
  container_name: webserver  
  ports:
   - "8000:80"   
  volumes:  
   - ./nginx/:/etc/nginx/conf.d/
